GN_Project/
└── Python/
    └── Centroid/
        ├── camera_package/
        │   ├── __init__.py                # Package initialization file
        │   ├── binary_image_processing.py  # Contains process_image function
        │   ├── crop_frame.py               # Contains crop_frame function
        │   └── centroid.py                  # Contains process_cnt function
        ├── camera.py                        # Contains grab_frame_from_camera function
        └── main.py                          # Main program to execute
